hero:
  title: Training
  subtitle: Morbi ornare arcu massa, a sodales augue vulputate quis. Nunc faucibus lectus augue, posuere pulvina
  ctaList:
    - title: Learn about our courses
      href: /learn/overview

info:
  - title: Awesome courses
    icon: icon-courses.svg
    body: Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pretium ligula nec mi facilisis malesuada. Donec sed massa finibus, laoreet tellus

  - title: Different levels
    icon: icon-level.svg
    body: Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pretium ligula nec mi facilisis malesuada. Donec sed massa finibus, laoreet tellus

  - title: Based on the community
    icon: icon-community.svg
    body: Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pretium ligula nec mi facilisis malesuada. Donec sed massa finibus, laoreet tellus

projects:
  - title: Training 1
    subtitle: By Xebia Functional
    body: Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pretium ligula nec mi facilisis malesuada.

  - title: Training 2
    subtitle: By Xebia Functional
    body: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie

  - title: Training 3
    subtitle: By Xebia Functional
    body: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie

  - title: Training 4
    subtitle: By Xebia Functional
    body: Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pretium ligula nec mi facilisis malesuada.

quotes:
  - name: Francico Díaz
    position: Principal at Xebia Functional
    image: quoted-person-a.jpg
    body: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est . Etiam eu turpis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est . Etiam eu turpis

  - name: Vicky Ruste
    position: Software Engineer
    image: quoted-person-b.jpg
    body: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est . Etiam eu turpis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est . Etiam eu turpis

navs:
  - title: Support
    href: /community/support
    icon: icon-support.svg
    body: Lorem ipsum dolor sit amet, consectetur adipiscing eliorem ipsum dolor sit amet

  - title: Blog
    href: /community/blog
    icon: icon-blog.svg
    body: Lorem ipsum dolor sit amet, consectetur adipiscing eliorem ipsum dolor sit amet

  - title: Events
    href: /community/events
    icon: icon-events.svg
    body: Lorem ipsum dolor sit amet, consectetur adipiscing eliorem ipsum dolor sit amet

banner:
  title: Want to know more about Λrrow?
  ctaList:
    - title: Read the docs
      href: /learn/overview
