// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  learnSidebar: [
    {
      type: 'autogenerated',
      dirName: 'learn',
    },
  ],
  ecosystemSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ecosystem',
    },
  ],
};

export default sidebars;
