// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  learnSidebar: [
    {
      type: 'autogenerated',
      dirName: 'learn',
    },
  ],
  incubationSidebar: [
    {
      type: 'autogenerated',
      dirName: 'incubation',
    },
  ],
};

module.exports = sidebars;
